name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Next.js app
        run: |
          npm run build

      - name: Export static site
        run: |
          npm run export

      - name: Install Capacitor CLI
        run: npm install @capacitor/cli --legacy-peer-deps

      - name: Install Capacitor Android
        run: npm install @capacitor/android --legacy-peer-deps

      - name: Initialize Capacitor Android platform
        run: npx cap add android

      - name: Copy web assets to Android
        run: npx cap copy

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Release Keystore
        run: |
          keytool -genkey -v -keystore release.keystore -alias pawly -keyalg RSA -keysize 2048 -validity 10000 -storepass pawly123 -keypass pawly123 -dname "CN=Pawly App,O=Pawly,L=Unknown,C=US"
        working-directory: android/app

      - name: Update Gradle Properties
        run: |
          echo "RELEASE_STORE_FILE=release.keystore" >> gradle.properties
          echo "RELEASE_KEY_ALIAS=pawly" >> gradle.properties
          echo "RELEASE_STORE_PASSWORD=pawly123" >> gradle.properties
          echo "RELEASE_KEY_PASSWORD=pawly123" >> gradle.properties
        working-directory: android

      - name: Build Release APK
        run: ./gradlew assembleRelease
        working-directory: android

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: pawly-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: pawly-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: android/app/build/outputs/apk/release/app-release.apk
          asset_name: pawly-release.apk
          asset_content_type: application/vnd.android.package-archive
